// import { Book } from './TableBooks';

export const data: any[] = [
  {
    id: '9s41rp',
    title: 'Kính Vạn Hoa',
    category: 'Sách Văn Học',
    price: '15000',
    quantity: 19,
    author: "string",
    publisher: "string",
    bookCover: "string",
    borrowCount: "string",
    description: "string",
    discount: "string",
    state: 'Ohio',
  },
  {
    id: '08m6rx',
    title: 'Sách Toán Lớp 12',
    category: 'Sách giáo dục',
    price: '5000',
    quantity: 37,
    author: "string",
    publisher: "string",
    bookCover: "string",
    borrowCount: "string",
    description: "string",
    discount: "string",
    state: 'Rhode Island',
  },
  {
    id: '5ymtrc',
    title: 'Sách Ngữ Văn',
    category: 'Sách giáo dục',
    price: '80000',
    quantity: 20,
    author: "string",
    publisher: "string",
    bookCover: "string",
    borrowCount: "string",
    description: "string",
    discount: "string",
    state: 'California',
  },
  {
    id: 'ek5b97',
    title: 'Sách Mỹ Thuật',
    category: 'Sách giáo dục',
    price: '90000',
    quantity: 38,
    author: "string",
    publisher: "string",
    bookCover: "string",
    borrowCount: "string",
    description: "string",
    discount: "string",
    state: 'Montana',
  },
  {
    id: 'xxtydd',
    title: 'Sách Sinh Học',
    category: 'Sách Tham khảo',
    price: '80000',
    quantity: 19,
    author: "string",
    publisher: "string",
    bookCover: "string",
    borrowCount: "string",
    description: "string",
    discount: "string",
    state: 'Colorado',
  },
  {
    id: 'wzxj9m',
    title: 'Dế mèn phiêu lưu kí',
    category: 'Truyện',
    price: '150002',
    quantity: 34,
    author: "string",
    publisher: "string",
    bookCover: "string",
    borrowCount: "string",
    description: "string",
    discount: "string",
    state: 'New York',
  },
  {
    id: '21dwtz',
    title: 'Wyman',
    category: 'Jast',
    price: 'Melvin.Pacocha@yahoo.com',
    quantity: 23,
    author: "string",
    publisher: "string",
    bookCover: "string",
    borrowCount: "string",
    description: "string",
    discount: "string",
    state: 'Montana',
  },
  {
    id: 'o8oe4k',
    title: 'Janick',
    category: 'Willms',
    price: 'Delfina12@gmail.com',
    quantity: 25,
    author: "string",
    publisher: "string",
    bookCover: "string",
    borrowCount: "string",
    description: "string",
    discount: "string",
    state: 'Nebraska',
  },
];

//50 us states array
export const states = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Puerto Rico',
];
