export const AUTH_LOGIN_SUCCESS:String="AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_FAIL:String="AUTH_LOGIN_FAIL"


export const AUTH_REGISTER_SUCCESS:String="AUTH_REGISTER_SUCCESS"
export const AUTH_REGISTER_FAIL:String="AUTH_REGISTER_FAIL"


export const AUTH_DELETE_ACCOUNT_SUCCESS:String="AUTH_DELETE_ACCOUNT_SUCCESS"
export const AUTH_DELETE_ACCOUNT_FAIL:String="AUTH_DELETE_ACCOUNT_FAIL"


export const GET_ALL_MESSAGE_SUCCESS:String="GET_ALL_MESSAGE_SUCCESS"
export const GET_ALL_MESSAGE_FAIL:String="GET_ALL_MESSAGE_FAIL"